### PR TITLE
(MODULES-8125) Fix unnecessary change when using intermediate certificates

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by absltkaos** [comment]
I just raised a small PR https://github.com/puppetlabs/puppetlabs-java_ks/pull/252 that does a subset of this one. If this gets merged, mine can just be closed out.

I would love to get this working... Does anyone have an ETA on when this will be merged etc...?

**Comment by johngmyers** [comment]
My experience shows this project takes one to two months to merge a PR. So ETA for merge would be late November/December if not allowing for holidays. Then it will be another few months for them to cut a release.

**Comment by johngmyers** [comment]
@david22swan My changes passed the Travis and Appveyor tests visible here. Where is the failure report and how can I run those tests?

**Comment by david22swan** [comment]
screen shot 2018-11-01 at 11 02 07 am

**Comment by david22swan** [comment]
Ok test's now passing green. Not sure where that failure came from but it repeated 3 times.
Happy to merge.

**Pull request merged**
