### PR TITLE
(FM-6457) Fix Windows CI

### PR DESCRIPTION
**Pull request by michaeltlombardi**
These commits fix problems with CI for Windows.

### CODE REVIEW

**Comment by pmcmaw** [comment]
@michaeltlombardi just to let you know I closed and reopened your PR to enable Appveyor.

**Comment by michaeltlombardi** [comment]
@pmcmaw: Looks like the Appveyor build is broken due to configuration?

**Comment by pmcmaw** [comment]
@michaeltlombardi Ive rekicked it. I enabled it without the configuration, it should start looking better in a few mins

**Comment by michaeltlombardi** [comment]
Awesome, thank you!

**Comment by pmcmaw** [comment]
No problem thats it now :-)

**Comment by michaeltlombardi** [comment]
Looks like the appveyor build is failing because it's trying to use nixy paths on Windows. :(

**Comment by michaeltlombardi** [comment]
@pmcmaw: All tests are green now. :)

**Pull request merged**
