### PR TITLE
Add an option to provide a password for keys in the keystore

### PR DESCRIPTION
**Pull request by ak0ska**
If set append the -destkeypass option when importing keys to the keystore.
This is not for security, but because certain applications require password protected key entries in the keystore.

### CODE REVIEW

**Comment by mhaskel** [comment]
Hi @ak0ska , thanks for this contribution and apologies it took us so long to review this. This largely looks good, but I have two comments. First, can `ks_keypassword` be renamed to `destkeypass`? We like to have the parameters line up with what is actually used in the commands as much as possible. Also, we need test updates for this new parameter. Thanks again, and let us know if you need a hand with anything!

**Comment by ak0ska** [comment]
Hello @mhaskel, before adding/modifying tests I wanted to run them, to see that the test framework works. Unfortunately I encounter an error (see output [1]) when running `rake beaker`. I tried on two machines (OSX, Ruby 2.1.2, Vagrant 1.6.2, and Ubuntu, Ruby 1.9.3, Vagrant 1.6.5), same results. 

Any idea what might be wrong? 

[1] http://pastebin.com/8B05Y5Tu

**Comment by mhaskel** [comment]
@ak0ska I run unit tests with `bundle exec rake spec` and acceptance tests with `bundle exec rspec spec/acceptance`, can you check and see if that works for you?

**Comment by ak0ska** [comment]
`bundle exec rake spec` runs fine (35 examples 5 deprecation warnings), but `bundle exec rspec spec/acceptance` produces the same error as `rake beaker`.

**Comment by mhaskel** [comment]
@ak0ska huh, well, I apparently can't run acceptance tests locally either right now :\

Not sure what's happening there, but looking into it.

**Comment by mhaskel** [comment]
Hi @ak0ska , sorry, this fell off my radar. I think the test issues has been resolved, if you run a `bundle update` then `bundle exec rspec spec/acceptance`.

**Comment by ak0ska** [comment]
I renamed it and added tests. Would you like me to rebase on master?

**Comment by mhaskel** [comment]
Hi @ak0ska, sorry I missed the notification for this. If you could rebase on master that would be great!

**Comment by DavidS** [comment]
Rebased this to a fresh PR. Thank you for your contribution, @ak0ska . The change looks really nice.

**Pull request closed without merging**
