### PR TITLE
Modules 4605: add timeout option

### PR DESCRIPTION
**Pull request by Mortinke**
#MODULES-4605

I added the timeout function to all commands which are executed. This function uses the new keytool_timeout parameter, which has the default value 0 => no timeout is used.

### CODE REVIEW

**Comment by tphoney** [comment]
@Mortinke This looks like a sensible and useful fix. Unfortunately you will need to do a rebase. Also could you please squash your commits. 

Great work, and many thanks

**Comment by Mortinke** [comment]
Hi @tphoney,

Sorry, I haven't written for ages, but I've been really busy in the last two weeks. I will rebase my comments next week and will try to create some tests. I have not had so much experience with puppet tests so I am looking forward to any help.

**Comment by tphoney** [comment]
No worries, life never really gets any less busy :)

**Comment by hunner** [comment]
Thanks @Mortinke! I have added tests in #179 and also changed the default to 120 seconds.

Sorry that this has been happening; it appears to be that the keytool command is returning before it has finished, and puppet then cleans up the tempdir which causes the keytool process to hang. I can't figure out why the tempfiles are removed, but at least the timeout keeps keytool from hanging puppet forever.

**Comment by tphoney** [comment]
Closing PR due to #179 being merged

**Pull request closed without merging**
