### PR TITLE
Extension parameter

### PR DESCRIPTION
**Pull request by albac**
The following contains feature support for JCEKS format and extensions.

Thanks!

### CODE REVIEW

**Comment by mhaskel** [comment]
Hi @albac! Sorry this fell off our radar for so long.

It looks like you haven't merged the PR from Ashley to add tests (https://github.com/albac/puppetlabs-java_ks/pull/1). That is necessary before we'll be able to merge this PR.

Also, it would be great if you could squash down all of your commits to a single commit. This also needs to be rebased against master. Thanks!

**Comment by tphoney** [comment]
@albac @apenney Could you please have a look at squashing the commits, adding the tests and rebasing. The work looks great, and it would be a great addition.

**Comment by tphoney** [comment]
Thanks for the work you have put in to this pull request. However due to inactivity and needing tests and a squash.
This pull request is being closed. If you want to re-submit this pr with the necessary changes, we will look at the new pull request.

**Comment by albac** [comment]
Hey guys, I understand why this was closed. I didn't have any time to go back to this in a while but finally I decided to do this again and I created a different pull request, thanks for you help!

**Pull request closed without merging**
