### PR TITLE
[GH-406] Fix storetype when creating new store

### PR DESCRIPTION
**Pull request by ricoapon**
See issue #406

### CODE REVIEW

**Comment by ricoapon** [comment]
Closed PR, because I cannot figure out how to get the tests working.

**Comment by pmcmaw** [comment]
Hey @ricoapon, I would like to apologize. With it being summer our team has been very light on resources. 
If this is something you are interested in I can help you if you would to reopen. Again i'm sorry this has been overlooked.

**Comment by ricoapon** [comment]
Hey @pmcmaw, thank you for your reaction! We discussed this morning that we are going to solve this maybe in another way, which means we don't need the fix. However, I would still like to build the fix, because it will give me some more Puppet/Ruby experience.

I am going on holiday for a few weeks, so that was the reason I closed it now. I do think I need some help. Is it ok if I contact you after the holiday period for some help?

**Comment by bartb** [comment]
This fixes an issue in our environment as well. So I would like to see this reopened. If I can help anyway, let me know.

We have an issue where there is a incorrect comparison (current and latest) between fingerprints of certificates with different chain lenghts. The "keytool -list -v -keystore" examines the keystore in pcks12 format and the "keytool -v -printcert -file" examines the certificate file in jks format.

**Pull request closed without merging**
